server:
  port: 8080

github:
  client:
    id: 7ded7b95e18ef1e9f9d4
    secret: d4dac18041a3c314322684e957e77631f485f00c
  redirect:
    uri: http://localhost:8080/callback


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true
    username: root
    password: jiao1995

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql